version: '3.1'

services:
  app:
    image: app
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
      MYSQL_PORT: 3307
  mysqldb:
    image: mysql
    ports:
      - "3307:3307"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: 123


